version: 2
updates:
  - package-ecosystem: npm
    directory: /packages/aws
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/web
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/media-handler
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /packages/api
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /packages/media-handler
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
