version: 2
updates:
  - package-ecosystem: npm
    directory: /cloud/aws
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /web/quipt
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /cloud/aws/lambda/mediaHandler
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /web/quipt
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /cloud/aws/lambda/mediaHandler
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
