version: '3.8'

services:
  services:
    image: tianon/true:latest@sha256:009cce421096698832595ce039aa13fa44327d96beedb84282a69d3dbcf5a81b
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.11.2@sha256:f3c62976f864b0087226991fe111e19122346f0f601c55eb2491190159dd07f9
    container_name: localstack
    environment:
      DATA_DIR: /tmp/localstack
      PORT_WEB_UI: 8081
      SERVICES: dynamodb,s3
      USE_SSL: "0"
    ports:
      - 4567-4584:4567-4584
      - ${PORT_WEB_UI-8081}:${PORT_WEB_UI-8081}
    volumes:
      - "${LOCALSTACK_DATA_VOL:-localstack_data_vol}:/tmp/localstack"

  web:
    build:
      context: ./web/quipt
    container_name: web
    image: ${REGISTRY_URI:-ghcr.io}/${REPOSITORY_NAME:-quipt/web}:${NAMED_TAG:-latest}
    ports:
      - 4200:4200

  api:
    build:
      context: ./api/
    image: ${REGISTRY_URI:-ghcr.io}/${REPOSITORY_NAME:-quipt/api}:${NAMED_TAG:-latest}
    container_name: api
    ports:
      - 3000:3000
