---
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  cdk-synth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          yarn --frozen-lockfile
          yarn workspace @quipt/aws build
          yarn workspace @quipt/aws cdk synth '**'

  angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0

      # Needed for generating the lockfile
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          yarn --frozen-lockfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: packages/web/
          push: false
          load: true
          tags: quipt:web-test
          target: test
          cache-from: type=gha,scope=web
          cache-to: type=gha,mode=max,scope=web

      - name: Test image
        run: |
          docker run quipt:web-test
