name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  cdk-synth:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: |
          cd cloud/aws
          yarn --frozen-lockfile
          yarn build
          yarn cdk synth
